<?php
/**
 * @author Steven Shaw
 * @copyright 2008
 */
function get_terms_of_use() {
	$termsOfUseText = 
"            Terms and Conditions for MightyUltimate.com
PLEASE READ THE FOLLOWING SECTIONS CAREFULLY BEFORE USING THE WEB SITE
Last modified: March 1, 2009

MightyUltimate.com (the 'Website') is an internet-based web site designed to let people sign up for ultimate frisbee leagues and hat tournaments (ultimate frisbee events).  It also provides a way for people to create and manage their own online based ultimate frisbee events.  Note that use of this Website is governed by specific Terms and Conditions (the 'Agreement'). Please read this Agreement carefully before registering with or fully accessing MightyUltimate.com. If you do not agree to these Terms and Conditions, you may not use the site to the full extent of its services. 

Mighty Ultimate Disc (the 'Company', 'We', 'Our', or 'Us') is a California-based sole proprietorship that has developed MightyUltimate.com. The Company reserves the right to update or modify this Agreement at any time, and without prior notification to site users. Your use of the Website, following such modifications or updates, indicates your acceptance of the revised Agreement. Therefore, you should regularly check when the Agreement was last modified and when changes occur, read through and review the Agreement.

Use Of The Web Site:
In order to use the Website, you must obtain access to the Internet, either directly or through devices that access web-based content, and pay any service fees associated with such access.  In addition, you must provide all equipment necessary to make such connection to the Internet, including a computer and modem or other access device.

1) While you are welcome to browse the Website, full usage requires that you create a player account and profile. If you use the Website without an player account and profile, you'll only have access to the public content area on the Website that includes listings for ultimate frisbee events and pickup games.
2) If you decide to fully use the Website, please complete both the player account and player profile forms.  This will allow you to register for any ultimate frisbee event that has room for players. If the player limits for a particular ultimate frisbee event have been reached, you will have the option to add your name to a wait list. To create a player account, you will need to provide: a player ID, a password, and an email address.  Please record your account's password in a safe location as it is your responsibility to maintain the security of the password.  If at any time you feel that the security of a password has been compromised, you can easily change the password by logging onto the Website and updating your account settings. The player profile form collects your contact information (address, phone numbers, emergency contact, etc...), information pertaining to your ultimate frisbee skills, your Ultimate Players Association (UPA) status and number (or the last 4 digits of your social security number if you forgot your UPA number), whether you are a student and whether you are over 18 years old.
3) With a player account, you will also be able to create an ultimate frisbee event and publish it after you have provided the appropriate event information and paid the required setup fee to Mighty Ultimate Disc.
4) You must be at least 18 years of age and have the legal right to agree to the Terms and Conditions to create an account for this Website. A parent or legal guardian, however, may establish an account for a minor.  Minors between the ages of 15 and 18 may use the Website and enter information, but their parent or guardian is responsible for supervising their use of the Website and for safeguarding their account information.  Minors under the age of 15 may not use the Website.
5) Please review the Terms and Conditions and the Privacy Policy carefully. If you agree, click the checkbox at the bottom of the screen. If you do not agree to all these Terms and Conditions and/or the Privacy Policy, you are not authorized to use the Website.

The Information We Collect:
1) We collect information that allows you to register for ultimate frisbee events.  This is limited to contact information and self assessed player skill information.
2) This Website places a cookie on your hard drive to maintain a session connection. This cookie does not contain any personally identifiable data.  Most browsers allow you to modify security settings so that you can approve or reject cookies on a case-by-case basis. Browsers typically offer instructions on how to reject cookies in the help section of their toolbar. To work correctly, out site requires that cookies and JavaScript be enabled. If you reject our cookie, you will not be able to login to our Website.
3) The Website may contain hyperlinks to other websites ('Other Sites'). If you use the hyperlinks to access these Other Sites, you will leave the Website and your browser will be re-directed to the Other Sites. The Other Sites may have their own terms of use and privacy policy and those Other Sites may have different practices and requirements than the Website.  Mighty Ultimate Disc/MightyUltimate.com may not have knowledge of, and is not responsible for, the content, information, services, products or advertisements presented by any Other Site which you use at your own risk. Mighty Ultimate Disc/MightyUltimate.com does not warrant or make any representation regarding the legality, accuracy, quality or authenticity of content, information, services or products presented by Other Sites. The hyperlinks to Other Sites do not constitute an endorsement by MightyUltimate.com of any Other Site(s) or resources, or their content, information, services or products. The Website is only providing these links to you as a convenience. The terms of use and privacy policy of any Other Sites shall apply to your access and use of them. Mighty Ultimate Disc/MightyUltimate.com accepts no responsibility for the content or conduct of Other Sites.
4) In setting up your account, you grant Mighty Ultimate Disc/MightyUltimate.com and all persons or entities involved in the operation of the Website the right to transmit, monitor, retrieve, store, and use the information you submit. By accessing this Website, you are agreeing to be bound by our Privacy Policy, which can be accessed on our home page. 

                       GENERAL TERMS AND CONDITIONS
Limited License:
The content of this Website is protected by copyright under United States laws. Title to the content remains with Mighty Ultimate Disc/MightyUltimate.com. Subject to the Terms and Conditions of this Agreement, you may access and use the content on this Website via your computer or other hand-held electronic devices for your own personal, non-commercial use. You are restricted to downloading and/or printing single copies of the content, provided you make no modifications of the content and all copyright and other proprietary notices remain intact. 

You are prohibited from publishing, licensing, creating derivative works from, transferring or selling any information, software, products or services obtained through MightyUltimate.com. Permission to reprint or electronically reproduce any document, or graphic in whole or in part for any commercial purpose is expressly prohibited, unless prior written consent is obtained from the Company. Moreover, you agree that you will not, and will not allow or aid or abet any third party (whether or not for your benefit), to copy, reverse engineer, reverse assemble or otherwise attempt to discover the source code used on the Website or insert any code, product or material to manipulate the content in any way that affects the user's experience. By completing the registration process on the Website, you establish an account with us and you represent that the information you provide in the player account and profile setup is accurate and current and that you will abide by the Terms and Conditions set forth in this document. Any use of the content not expressly permitted by these Terms and Conditions is a breach of these Terms and Conditions.

Trademarks:
The trademarks, logos, service marks, and trade names (collectively the Trademarks) shown on the Website or on content made available through the Website are registered and unregistered Trademarks of Mighty Ultimate Disc. All Trademarks not owned by Mighty Ultimate Disc are the property of their respective owners. All Trademarks, whether owned by Mighty Ultimate Disc or others, may not be used in connection with any products or services that are not related to, associated with, or sponsored by their owners. Nothing contained on the Website should be construed as granting, by implication, estoppel or otherwise, any license or right to use any Trademark displayed on the Website without the explicit written permission of Mighty Ultimate Disc or the third party that may own the applicable Trademark. Any misuse of the Trademarks displayed on the web is strictly prohibited.

Termination of Services:
Mighty Ultimate Disc reserves the right, in its sole discretion, to immediately and without any prior notice to suspend or terminate (i) these Terms of Use; (ii) your registration with or ability to access the Website and/or any other service provided to you by Mighty Ultimate Disc upon; (a) any breach by you of these Terms of Use or upon your demonstration of conduct that Mighty Ultimate Disc determines to be inappropriate; (b) requests by law enforcement or other government agencies, (c) a request by you (self-initiated account deletions), (d) discontinuance or material modification to the Website, (e) unexpected technical or security issues or problems, (f) extended periods of inactivity, (g) engagement by you in fraudulent or illegal activities, and/or (h) nonpayment of any fees owed by you in connection with services provided by the Website. All records, information, messages, content and other information related to your registration and account may also be deleted by Mighty Ultimate Disc in its sole discretion without any notice or liability to you. Mighty Ultimate Disc shall not be liable to you or any third party for any termination of your account, any associated account related or identifying information, or access to the Website.

The following provisions survive the expiration or termination of this Agreement for any reason whatsoever: Indemnity, Jurisdiction, Complete Agreement and Assignment, Liability of Mighty Ultimate Disc/MightyUltimate.com and Disclaimers, User Submissions, Third Party Content and Information, and Proprietary Rights.

Indemnity:
You agree to defend, indemnify and hold harmless Mighty Ultimate Disc, its officers, directors, employees, agents, licensors, and suppliers, from and against any claims, actions or demands, losses, liabilities and settlements including without limitation, reasonable legal and accounting fees, resulting from or alleged to result from any breach or violation of these Terms and Conditions. You will cooperate as fully and reasonably as required by Mighty Ultimate Disc/MightyUltimate.com in the defense of any claim. Notwithstanding the foregoing, Mighty Ultimate Disc retains the exclusive right to settle, compromise and pay any and all claims, demands, proceedings, suits, actions or causes of actions which are brought against Mighty Ultimate Disc/MightyUltimate.com herein under the terms and provisions of this section and in no event shall you settle any such claim without Mighty Ultimate Disc's prior written approval.

Jurisdiction:
You agree that this Agreement is entered between you and Mighty Ultimate Disc in the State of California, United States of America, and shall be construed and governed in all respects under the laws of the State of California. You expressly agree that exclusive jurisdiction for any dispute with Mighty Ultimate Disc/MightyUltimate.com resides in the courts of the State of California and you further agree and expressly consent to the exercise of personal jurisdiction in the courts of the State of California in connection with any such dispute, including any claim involving Mighty Ultimate Disc/MightyUltimate.com or their affiliates, subsidiaries, employees, contractors, officers, directors, telecommunication providers, and content providers.  These Terms and Conditions are governed by the internal substantive laws of the State of California, without respect to its conflict of laws principles. If any provision of these Terms and Conditions is found to be invalid by any court having competent jurisdiction, the invalidity of such provision shall not affect the validity of the remaining provisions of these Terms and Conditions, which shall remain in full force and effect. No waiver of any of these Terms and Conditions shall be deemed a further or continuing waiver of such term or condition or any other term or condition. 

Complete Agreement and Assignment:
Except as expressly provided in a particular legal notice posted on MightyUltimate.com web site, the Terms and Conditions and the Privacy Policy constitute the entire agreement between you and Mighty Ultimate Disc with respect to use of the Website and its content. We may assign this contract at any time in our sole discretion to a subsidiary, an affiliated company, or as part of the sale, merger or transfer of the Company to another entity. We will post a notice on the Website regarding any change of ownership so that may discontinue using the site or cancel your registration if you do not wish to continue accessing its services under new ownership.

Liability of Mighty Ultimate Disc/MightyUltimate.com and Disclaimers:
1) If you create your own ultimate frisbee event on the Website, you are solely responsible for collecting payment from players who participate in your event.
2) If you create your own UPA sanctioned ultimate frisbee event, you are solely responsibile for collecting the appropriate UPA forms and documents and submitting them to the UPA.
3) If you register to play in an ultimate frisbee event created on the Website, your registration and other event fees are solely owed to the person who created the event on the Website (the 'Event Organizer').  Event participants do not pay registration or other event fees to Mighty Ultimate Disc.
4) If you participate in an ultimate frisbee event created on the Website, you do so at your own risk.
5) The Website does not warrent that it will be uninterrupted, secure or error free. The Website does not warrant or guarantee any information, products, services, or merchandise we mention. The content on the Website is provided on an as is and as available basis without any warranty, either express or implied, as to the accuracy, reliability, completeness, and timeliness of the content, software, text, graphics, or communications on the Website or through use of the Website and its links.
6) Questions or comments regarding this Website, including any reports of non-functioning features or links, should be  submitted by e-mail via our online web form. We will try to answer every e-mail but may not always be able to do so on a timely basis.
7) There is no liability for damages. In no event shall Mighty Ultimate Disc/MightyUltimate.com be liable for damages (including, but not limited to, personal injury, wrongful death, lost revenue or profits, or damages from lost data or business interruption) as the result of: (a) the use or the inability to use the Website; (b) the cost of procurement of substitutive goods and services resulting from any goods, data, information or services purchased or obtained or messages received or transactions entered into through or from the Website; (c) personal injury not caused by Mighty Ultimate Disc's gross negligence; (d) unauthorized access to or alteration of your transmissions or data; (e) statements or conduct of any third party on the Website; or (f) any other matter concerning the Website. You agree that Mighty Ultimate Disc's maximum liability to you, for any reason or cause whatsoever, shall not exceed the total amount of monies received by Mighty Ultimate Disc from you.  The sole and exclusive remedy for dissatisfaction with the services of this site will be to stop using MightyUltimate.com.

User Submissions:
You agree and acknowledge that you are solely responsible for the accuracy, truthfulness, completeness and content of any and all material (text and media) you submit to the web site. You acknowledge that Mighty Ultimate Disc/MightyUltimate.com does not assume any liability for any information you submit or your use of information or tools available on the Website. Furthermore, you agree to indemnify Mighty Ultimate Disc/MightyUltimate.com and its affiliates, directors, officers and employees and to hold them harmless from any and all claims and expenses, including attorneys fees, arising from the materials/media you submit and/or your failure to comply with our Terms and Conditions.

Minors: Minors under the age of 15 may not use the Website. Minors, ages 15 and up, may enter information into the accounts established for them by their parent or guardian. However, you, as the parent or guardian, are still responsible for supervising each minor's use of the Website and for safeguarding registration information. For each minor, you also assume full responsibility for overseeing the accuracy of entered data, the creation of any ultimate frisbee event, the payment of any ultimate frisbee event setup fee, and the submission of any video images, photos, or text to the Website.

All Users: Mighty Ultimate Disc/MightyUltimate.com reserves the right to remove from the Website at its discretion any controversial, defamatory and copyright infringing material or to edit or modify material flagged by other users as inappropriate, inaccurate, or not for public disclosure (e.g., unpublished research findings). To use the Website, you must agree to comply with all user responsibilities and obligations stated in these Terms of Service, as follows:  

You will not use the Website to:
1) Upload, post, e-mail, transmit, display, copy, distribute, promote, or otherwise communicate to the public:
	i) any material that is false, unlawful, threatening, tortious, disparaging, anything that adversely affects MightyUltimate.com such as discouraging any person or entity from advertising with, linking to or supplying MightyUltimate.com, abusive, libellous, defamatory, obscene, vulgar, offensive, pornographic, profane, racist, sexually explicit, ethnically or culturally offensive, indecent, or that promotes violence, racial hatred, terrorism, or illegal acts, or is otherwise objectionable in MightyUltimate.com's sole discretion;
	ii) information, software, content or other material that violates, plagiarises, misappropriates or infringes the rights of third parties including, without limitation, copyright (including, offering pirated computer programs or links to such programs, information used to circumvent manufacturer-installed copy-protect devices, including serial registration numbers for software programs, rights management information or any type of cracker utilities), trademark, patent, trade secret, rights of privacy or publicity, confidential information or any other proprietary right;
	iii) material of any kind that contains a virus, Trojan horse, time bombs, worms, spyware, adware, malware, bots, any automated use of the system, such as scripts, or other harmful component or restricts or inhibits any other user's uninhibited use and enjoyment of MightyUltimate.com, interferes with, overburdens, impairs or disrupts the MightyUltimate.com or servers or networks connected to MightyUltimate.com, or disobeys any requirements, procedures, policies or regulations of networks connected to MightyUltimate.com;
	iv) information or material of any kind that is false or misleading or that constitutes or contains false or misleading indications of origin or statements of fact, including, without limitation, by forging any TCP/IP packet header, any part of the header information in any transmission to the Website, or otherwise manipulating identifiers in order to disguise the origin of any content transmitted to or from the Website; or
	v) any unsolicited or unauthorised advertising, promotional materials, junk mail, spam, chain letters, pyramid schemes, requests for money, petitions for signature, or any other form of solicitation.
2) Encourage, promote, solicit or commit conduct that would constitute a criminal offence, give rise to civil liability or otherwise violate any local, state, national or international law or otherwise make available any material that exploits or harms any individual, corporation or other entity.
3) Use an inappropriate player ID of any kind;
4) Impersonate any person or entity or falsely state or otherwise misrepresent your affiliation with a person or entity;
5) Stalk, abuse, sexually exploit, violently exploit, groom, act violently toward, threaten or otherwise harass another user;
6) Target or harm minors in any way;
7) Use or attempt to use another's information, account, password, service or system except as expressly permitted;
8) Solicit or collect personal data including telephone numbers, addresses, last names, email addresses, or any other kind of information about users, including without limitation, through such means as spidering, screen scraping, database scraping, harvesting of e-mail addresses, wireless addresses or other contact or personal information, or any other automatic means of accessing, logging-in or registering on the Website or for any services or features offered on or through the Website; and
9) Undertake any commercial purpose or activity without the prior written consent of Last.fm, including, for example and without limitation, inserting your own or a third party's advertising, branding or promotional content into any of the Website's content, materials or services.

You represent, warrant and agree that you will comply with the above acceptable use requirements. Mighty Ultimate Disc/MightyUltimate.com reserves the right, in its sole discretion, to terminate any user's account or take such other action as the Company sees fit in relation to any user who breaches acceptable use policy or any of the other terms set forth herein. In extreme cases or as required by law or regulation, the Company reserves the right to take court action and/or report users to the relevant authorities. Mighty Ultimate Disc/MightyUltimate.com believes in building a caring community based around playing ultimate frisbee and will not tolerate antisocial or unlawful behaviour on the Website.

Third Party Content and Information:
MightyUltimate.com contains content and information that is provided for your convenience and enjoyment. Third parties provide some of the content and information. You should be aware that the content might contain errors, omissions, inaccuracies, outdated information and inadequacies and that the content may be subject to terms and conditions, which may be found on the Website or in the documents and policies of third parties.  MightyUltimate.com makes no representations or warranties as to the completeness, accuracy, adequacy, currency or reliability of any content and will not be liable for any lack of the foregoing.

In addition, you may order services or merchandise through the Website from other persons not affiliated with Mighty Ultimate Disc ('Seller'). For example, you may choose to register for an ultimate frisbee event and purchase event-related merchandise via the Website. All matters concerning the merchandise and services desired from a Seller, including but not limited to purchase terms, payment terms, warranties, guarantees, maintenance and delivery, are solely between you and the Seller. Mighty Ultimate Disc makes no warranties or representations whatsoever with regard to any goods or services provided by Sellers. You will not consider Mighty Ultimate Disc, nor will Mighty Ultimate Disc be construed as, a party to such transactions, whether or not Mighty Ultimate Disc may have received some form of revenue or other remuneration in connection with the transaction. You agree that Mighty Ultimate Disc will not be liable for any costs or damages arising out of such transactions, either directly or indirectly.

Descriptions of, or references to, products, services or publications within the Website do not imply endorsement of that product, service or publication.

Proprietary Rights:
If you submit any business idea, information, concept or invention to Mighty Ultimate Disc/MightyUltimate.com via e-mail, mail, blog, or through the public area or the Website, you agree such submission is non-confidential for all purposes. You automatically grant or warrant that the owner of such content or intellectual property has expressly granted Mighty Ultimate Disc/MightyUltimate.com a royalty-free, perpetual, irrevocable, world-wide, nonexclusive license to use, reproduce, modify, publish, edit, translate, distribute, perform and display the communication or content in any media or medium, any form, format, or forum now know or hereafter developed. Confidential information for which you wish to retain a proprietary interest should not be submitted directly to Mighty Ultimate Disc/MightyUltimate.com.

Review of Member Postings and Uploads:
Mighty Ultimate Disc/MightyUltimate.com does not claim a copyright to the personal text, files, images, photos that you post on the Website. You are legally responsible for all content that is posted through your player account to MightyUltimate.com web site. In posting this material, you represent that you own this posted content or otherwise have the right to post this content. After posting of such content, you shall continue to retain ownership of the member content. However, you must agree that any informational submission or communication is non-confidential and may be reproduced in part or whole and edited and modified at the discretion of Mighty Ultimate Disc/MightyUltimate.com.

1) Informational content is subject to copyright law and to our privacy policy. You must agree not to upload or transmit any content that may infringe upon or violate any rights of another party, including but not limited to copyrighted materials, trade secrets, unpublished research, and medical record information.
2) Mighty Ultimate Disc/MightyUltimate.com assumes no responsibility for monitoring of content posted by site users. We do not and cannot review all content posted or uploaded to the site.
3) We do encourage you to report inaccurate, faulty, misleading, offensive, obscene, hateful, illegal, defamatory, and libelous content by flagging content as inappropriate. Mighty Ultimate Disc/MightyUltimate.com reserves the right to remove at its discretion, to edit or modify material flagged by its members along with any controversial, defamatory, copyright infringing material identified by its staff.
4) To protect the rights of copyright owners, Mighty Ultimate Disc/MightyUltimate.com maintains a policy for the termination of registrants who are repeat infringers of copyright laws.
5) Materials posted and/or uploaded to the public section of the Website may be subject to size and other limitations. You are responsible for adhering to such limitations.

Notification of Possible Copyright Infringement:
If you believe any materials on MightyUltimate.com web site infringe your copyright, you may request removal of those materials by contacting Mighty Ultimate Disc. All notices must meet the current statutory requirements imposed by the Digital Millennium Copyright Act of 1998 (DMCA). At minimum, you must provide the following information:
1) Identification of the specific information that you believe should not be posted and its location on MightyUltimate.com web site (with URL).
2) Detail on the original source of this information and its URL or other relevant detail, such as publication name/date/volume/page.
3) Your name, address, e-mail address, and telephone number.
4) A statement that the information you supplied is accurate and that you are the copyright owner or authorized agent for the owner. The statement must be signed or submitted with an electronic equivalent. 
5) Send the statement to Mighty Ultimate Disc at 55 Bridge Rd, Novato, CA 94945

Pricing:
Pricing Information Disclosure For California Residents. Under California Civil Code Section 1789.3, California residents that access the Website are entitled to the following specific consumer rights information: (i) Pricing Information - Current rates for using the Website may be obtained by going to the home page on the Website located at http://mightyultimate.com/index.php  Mighty Ultimate Disc reserves the right to change any fees, pricing or charges or to institute new fees at any time; (ii) Complaints - The Complaint Assistance Unit of the Division of Consumer Services of the California Department of Consumer Affairs may be contacted in writing at 1020 N. Street, #501, Sacramento, CA 95814, or by telephone at 1-916-445-1254.

Privacy:
Registration data and certain other information about you are subject to our Privacy Policy. Please read the Privacy Policy for information on how your personal data and other information about you will be handled. By accepting these Terms of Use you are also accepting the terms of the Privacy Policy, which is incorporated herein by reference for all purposes.";
	return $termsOfUseText;
}
?>